import assert from 'node:assert/strict';
import {buildMaze} from '../src/maze.mjs';import {addSurfaceSpikes,touchesSpikes,trapSupported} from '../src/traps.mjs';
import {createRewards,collectReward} from '../src/rewards.mjs';import {createMagic,castLight,updateMagic} from '../src/magic.mjs';import {startDash} from '../src/physics.mjs';import {ordinaryWall,breakWall} from '../src/breach.mjs';import {updateTornadoes} from '../src/tornado.mjs';
const w=buildMaze();w.mazeHeight=w.H;addSurfaceSpikes(w);assert.ok(w.traps.some(t=>t.angle===Math.PI));assert.ok(w.traps.some(t=>Math.abs(t.angle)===Math.PI/2));
for(const angle of [0,Math.PI,Math.PI/2,-Math.PI/2]){const t={x:100,y:100,w:64,angle};const p={x:100+32*Math.cos(angle)+15*Math.sin(angle),y:100+32*Math.sin(angle)-15*Math.cos(angle)};assert.ok(touchesSpikes(p,t,4));assert.equal(touchesSpikes(p,t,1),false)}
const p={wing:.7,hp:3,face:1,x:0,y:0},r=createRewards(w).filter(r=>r.kind==='relic');for(const item of r)collectReward(item,p,.7,0);assert.deepEqual(p.abilities,{spread:true,dash:true,breach:true});assert.ok(startDash(p));assert.equal(p.dashCooldown,.6);
const m=createMagic();castLight(m,p,0);assert.equal(m.shots.length,3);updateMagic(m,.1,.1,{solid:()=>false,targets:[],hit:()=>{}});assert.ok(m.shots[0].y<0&&m.shots[2].y>0);
let shots=[{x:50,y:50,dx:1,dy:0,bounces:0,life:7}],max=0;for(let i=0;i<200&&shots.length;i++){shots=updateTornadoes(shots,.02,{free:(x,y,r)=>x-r>0&&x+r<100,player:{x:999,y:999},hurt:()=>{}});if(shots.length)max=Math.max(max,shots[0].bounces)}assert.equal(max,2);assert.equal(shots.length,0);
const map=Array.from({length:15},(_,y)=>Array.from({length:15},(_,x)=>x===6||x===7||x===8||x<2||y<2||x>=13||y>=13?1:0));const ww={map,T:32,W:15,mazeHeight:15};const miner={x:176,y:240,face:1,energy:30,abilities:{breach:true}};const wall=ordinaryWall(miner,ww,null);assert.ok(wall);assert.ok(breakWall(miner,wall,map,32,[]));assert.equal(miner.energy,0);assert.equal(map[7][6],0);miner.x=76;miner.face=-1;assert.equal(ordinaryWall(miner,ww,null),null);assert.equal(trapSupported({x:192,y:224,w:32,angle:Math.PI/2},(x,y)=>map[Math.floor(y/32)]?.[Math.floor(x/32)]===1),false);
console.log('PASS surface spikes in four directions, three relic abilities, triple spread, half cooldown, two reflections, ordinary walls and boundary protection');
