const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});try{const p=await b.newPage({viewport:{width:1100,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/game.js',async r=>r.fulfill({contentType:'application/javascript',body:fs.readFileSync('src/game.js','utf8')+`
window.test={solid,free,reset,pressAttack,releaseAttack,pause,resume,attack,update,render,applyMelee,get p(){return player},get rats(){return rats},get magic(){return magic},get slash(){return slash},get fauna(){return fauna},get charging(){return chargeStart},tick(n){for(let i=0;i<n;i++)update(.01)},clock(t){time=t},get time(){return time},clean(){rats.forEach(r=>r.hp=0);fauna.birds.forEach(r=>r.hp=0);fauna.trees.forEach(r=>r.hp=0);player.inv=9999},target(){const r=rats[0];player.x=r.x-50;player.y=r.y;player.face=1;player.inv=9999;r.hp=10;r.stun=9999;return r}};`}));await p.addInitScript(()=>window.requestAnimationFrame=()=>1);await p.goto((process.env.BASE_URL||'http://127.0.0.1:8768/')+'?legacy=1');await p.click('#start');
let result=await p.evaluate(()=>{test.reset();test.clean();const r=test.target();test.pressAttack();test.releaseAttack();const first=[test.slash.stage,r.hp];test.pressAttack();test.releaseAttack();test.pressAttack();test.releaseAttack();test.tick(33);const second=[test.slash.stage,r.hp];const x=test.p.x;test.tick(33);const third=[test.slash.stage,r.hp];test.tick(12);test.render();return {first,second,third,dx:test.p.x-x}});assert.deepEqual(result.first,[1,9]);assert.deepEqual(result.second,[2,8]);assert.deepEqual(result.third,[3,7]);assert.ok(result.dx>20);await p.screenshot({path:'tests/artifacts/combo-cross.png'});
result=await p.evaluate(()=>{test.clock(test.time+1);test.target();test.pressAttack();test.releaseAttack();return test.slash.stage});assert.equal(result,1);
await p.evaluate(()=>{test.reset();test.clean();test.pressAttack();test.tick(81);test.render()});await p.screenshot({path:'tests/artifacts/charge-magic.png'});await p.keyboard.press('p');assert.equal(await p.evaluate(()=>test.charging),null);await p.keyboard.press('p');await p.evaluate(()=>test.releaseAttack());assert.equal(await p.evaluate(()=>test.magic.shots.length),0);
result=await p.evaluate(()=>{test.reset();test.clean();test.pressAttack();test.clock(.81);test.releaseAttack();const shot=test.magic.shots[0];return {damage:shot.damage,charged:shot.charged}});assert.deepEqual(result,{damage:1.5,charged:true});
result=await p.evaluate(()=>{test.reset();test.clean();const r=test.rats[0];test.p.x=r.x-50;test.p.y=r.y;test.p.face=1;r.hp=0;r.stun=9999;test.pressAttack();test.clock(.81);test.releaseAttack();r.hp=2;test.tick(15);const hp=r.hp;test.p.x=r.x-40;test.p.y=r.y;test.attack();return {hp,dead:r.hp}});assert.deepEqual(result,{hp:.5,dead:0});
await p.evaluate(()=>{test.reset();test.clean();test.fauna.tornadoes.push({x:test.p.x+50,y:test.p.y,dx:1,dy:0,bounces:0,life:7});test.render()});await p.screenshot({path:'tests/artifacts/coil-tornado.png'});
result=await p.evaluate(()=>{test.reset();test.clean();test.target();let wall=test.p.x;while(!test.solid(wall,test.p.y)&&wall<test.p.x+500)wall++;test.p.x=wall-12;test.attack(3);test.tick(18);return {stopped:test.p.x<wall-10,free:test.free(test.p.x,test.p.y)}});assert.deepEqual(result,{stopped:true,free:true});
if(process.env.TEST_MOBILE){await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{test.reset();test.clean();test.render()});await p.locator('[data-key=attack]').dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch'});await p.evaluate(()=>test.clock(.81));await p.locator('[data-key=attack]').dispatchEvent('pointerup',{pointerId:1,pointerType:'touch'});assert.equal(await p.evaluate(()=>test.magic.shots[0]?.damage),1.5);await p.locator('#motion').evaluate(e=>e.click());await p.evaluate(()=>test.render());await p.screenshot({path:'tests/artifacts/combo-mobile.png'});}assert.deepEqual(errors,[]);console.log('PASS queued triple combo, once per swing, lunge, combo timeout, charge, pause cancellation, fractional rat damage/death, desktop input and VFX (mobile opt-in)');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});

