const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/game.js',async r=>r.fulfill({contentType:'application/javascript',body:fs.readFileSync('src/game.js','utf8')+`\nwindow.a={resume,world,update,reset,render,breach,attack,pressAttack,releaseAttack,saveCheckpoint,captureCheckpoint,restoreCheckpoint,hurt,keys,get p(){return player},get rats(){return rats},get fauna(){return fauna},get env(){return exploration},get walls(){return crackedWalls},get boss(){return boss},get mode(){return mode},tick(n){for(let i=0;i<n;i++)update(1/60)}};`}));await p.addInitScript(()=>window.requestAnimationFrame=()=>1);await p.goto(process.env.BASE_URL||'http://127.0.0.1:8768/');await p.click('#start');
const intro=await p.evaluate(()=>{a.p.inv=1e9;a.keys.add('right');for(let i=0;i<300;i++)a.update(1/60);a.keys.clear();a.tick(40);const before={energy:a.p.energy,discovered:a.walls[0].discovered,x:a.p.x};a.breach();a.tick(1);a.render();return {before,broken:a.walls[0].broken,active:a.env.winds[0].active,energy:a.p.energy}});console.log('intro',intro);assert.equal(intro.before.energy,30);assert.ok(intro.before.discovered);assert.ok(intro.active);assert.equal(intro.energy,0);await p.screenshot({path:'tests/artifacts/adventure-first-breach.png'});
const route=await p.evaluate(()=>{const w=a.world;let steps=0;function go(n){const target=w.position(n);for(let i=0;i<1800;i++){const dx=target.x-a.p.x,dy=target.y-a.p.y;a.keys.clear();if(Math.abs(dx)<18&&Math.abs(dy)<24)return;if(Math.abs(dx)>14)a.keys.add(dx>0?'right':'left');if(dy<-12)a.keys.add('up');else if(dy>25)a.keys.add('down');a.update(1/60);steps++;if(a.boss.active)return;if(i===1799)throw Error('stuck '+JSON.stringify({n,target,p:a.p}))}}
// Wind return loop, then full authored spine. Damage is isolated for traversal validation.
for(const n of [206,186,166,165,164,163,162,161,181,201])go(n);
for(const n of w.main){go(n);if(a.boss.active)break}a.keys.clear();a.render();return {steps,lights:levelSnapshot().lights.filter(l=>l.got).length,boss:a.boss.active,time:levelSnapshot().time}});console.log('route',route);assert.equal(route.lights,3);assert.ok(route.boss);const won=await p.evaluate(()=>{a.p.x=a.boss.x-70;a.p.y=a.boss.y;a.p.face=1;for(let i=0;i<30;i++)a.attack();a.p.x=a.world.arena.exit.x;a.p.y=a.world.arena.exit.y;a.tick(1);return a.mode});assert.equal(won,'won');await p.screenshot({path:'tests/artifacts/adventure-boss-route.png'});
// Save round trip: map destruction, dynamic children, echoes, enemies, no transient attacks.
const save=await p.evaluate(()=>{a.reset();a.resume();a.p.inv=1e9;a.p.energy=100;const wall=a.walls[0];a.p.x=wall.x-25;a.p.y=wall.y+48;a.p.face=1;a.breach();a.env.echoes[0].got=true;a.env.obstacles[0].hp=0;a.env.obstacles[0].broken=true;a.fauna.trees[0].hp=0;const big=a.rats.find(r=>r.big);big.hp=0;a.tick(1);a.rats[0].hp=.5;a.fauna.zones[0].seen=true;a.fauna.zones[0].elapsed=.7;a.p.hp=2.5;a.p.abilities.spread=true;a.saveCheckpoint();const s=a.captureCheckpoint();a.restoreCheckpoint(s);a.render();return {hp:a.p.hp,rat:a.rats[0].hp,children:a.rats.filter(r=>r.child).length,wall:a.walls[0].broken,wind:a.env.winds[0].active,echo:a.env.echoes[0].got,stumps:a.world.platforms.filter(p=>p.id?.startsWith('stump')).length}});assert.deepEqual(save,{hp:2.5,rat:.5,children:4,wall:true,wind:true,echo:true,stumps:1});
await p.reload();await p.waitForSelector('#continue:not([hidden])');await p.click('#continue');assert.equal(await p.evaluate(()=>a.p.hp),2.5);assert.equal(await p.evaluate(()=>a.env.winds[0].active),true);
await p.keyboard.press('p');await p.screenshot({path:'tests/artifacts/adventure-pause.png'});assert.equal(await p.locator('#pause-details').isVisible(),true);await p.locator('#motion').click();await p.keyboard.press('p'); // button focus requires resume button
await p.evaluate(()=>a.render());
for(const v of [{width:1280,height:720},{width:1920,height:1080}]){await p.setViewportSize(v);await p.evaluate(()=>a.render());assert.equal(await p.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);assert.equal(await p.locator('#magic').isVisible(),false)}
const branches=await p.evaluate(()=>{a.reset();a.resume();a.p.inv=1e9;let steps=0;for(const b of a.world.branches){Object.assign(a.p,a.world.position(b.nodes[0]),{vy:0,wing:.7});for(const n of b.nodes){const target=a.world.position(n);for(let i=0;i<1800;i++){const dx=target.x-a.p.x,dy=target.y-a.p.y;a.keys.clear();if(Math.abs(dx)<15&&Math.abs(dy)<18)break;if(Math.abs(dx)>10)a.keys.add(dx>0?'right':'left');if(dy<-10)a.keys.add('up');else if(dy>25)a.keys.add('down');if(i%21===0){a.pressAttack();a.releaseAttack()}a.update(1/60);steps++;if(i===1799)throw Error('branch stuck '+JSON.stringify({n,p:a.p,obstacles:a.env.obstacles}))}}a.tick(1)}a.keys.clear();return {relics:levelSnapshot().rewards.filter(r=>r.kind==='relic'&&r.got).length,echoes:a.env.echoes.filter(e=>e.got).length,steps}});assert.deepEqual([branches.relics,branches.echoes],[3,3]);console.log('six branch traversals',branches);
const interaction=await p.evaluate(()=>{a.reset();a.resume();a.p.inv=1e9;const out=[];for(const o of a.env.obstacles){a.p.x=o.x-45;a.p.y=o.y;a.p.face=1;a.pressAttack();a.releaseAttack();for(let k=0;k<o.stage-1;k++){a.pressAttack();a.releaseAttack();a.tick(20)}out.push(o.broken);a.tick(60)}return out});assert.deepEqual(interaction,[true,true,true]);
const lamps=await p.evaluate(()=>{a.reset();a.resume();a.tick(1);a.p.hp=3;a.p.x+=65;a.tick(1);a.p.x-=65;a.tick(1);const s=JSON.parse(localStorage.getItem('eye-creature.adventure.checkpoint'));return {hp:a.p.hp,saved:s.state.player.hp}});assert.deepEqual(lamps,{hp:3,saved:3});
await p.keyboard.press('p');p.once('dialog',d=>d.dismiss());await p.click('#restart');assert.equal(await p.evaluate(()=>a.p.hp),3);await p.click('#start');
// Corrupt/incompatible snapshots stay untouched and offer a fresh start, not a crash.
await p.evaluate(()=>localStorage.setItem('eye-creature.adventure.checkpoint',JSON.stringify({format:999,version:'old'})));await p.reload();await p.locator('#start:not([disabled])').waitFor();assert.equal(await p.locator('#continue').isVisible(),false);assert.ok((await p.locator('#save-status').textContent()).includes('保留'));assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('eye-creature.adventure.checkpoint')).format),999);
const blocked=await b.newPage();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw new Error('quota')};});await blocked.goto(process.env.BASE_URL||'http://127.0.0.1:8768/');await blocked.click('#start');await blocked.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('無法保存'));assert.equal(await blocked.evaluate(()=>levelSnapshot().mode),'playing');await blocked.close();
assert.deepEqual(errors,[]);console.log('PASS desktop gameplay, intro wind loop, all lights to boss, checkpoint round trip, reload, menus, layouts');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});



